"""Geocoding for tournaments_data.json, run by geocode_tournaments.py after each scrape.

Modules, lowest first (a module only imports from those before it):
common, places, geonames, coast, beachfront, airports, nominatim, geocoder,
pipeline.
"""

from geocoding.airports import (
    AIRPORT_SEARCH_DEG,
    AIRPORTS_FILE,
    LARGE_AIRPORT_DETOUR_KM,
    MAX_AIRPORT_KM,
    Airports,
)
from geocoding.beachfront import (
    BEACHFRONT_M,
    COASTLINE_SEARCH_M,
    M_PER_DEG_LAT,
    M_PER_DEG_LNG_EQUATOR,
    OVERPASS_RETRY_WAIT_S,
    OVERPASS_URLS,
    VENUE_CATEGORIES,
    VENUE_MAX_KM,
    VENUE_NAME_MIN_LEN,
    km_between,
    metres_to_segment,
    names_match,
    overpass_coastline,
    sea_distance_m,
)
from geocoding.coast import (
    ATLANTIC_FEDS,
    COAST_FILE,
    EARTH_DIAMETER_KM,
    GRID_DEG,
    SEASIDE_KM,
    Coast,
    seaside_coast,
)
from geocoding.common import (
    DEFAULT_MAX_LOOKUPS,
    MISS_RETRY_DAYS,
    NETWORK_ERRORS,
    NOMINATIM_URL,
    REQUEST_INTERVAL_S,
    SAVE_EVERY,
    USER_AGENT,
    logger,
)
from geocoding.geocoder import (
    OVERRIDES_FILE,
    Geocoder,
)
from geocoding.geonames import (
    ADMIN_WORDS,
    ARTICLES,
    CONNECTORS,
    GENERIC_PLACE_WORDS,
    GEONAMES_COLUMNS,
    MAX_NGRAM,
    MIN_NAME_LEN,
    PROVINCE_SEATS,
    VENUE_WORDS,
    Place,
    flags,
    geonames_match,
    load_geonames,
    normalise,
    town_from_name,
)
from geocoding.nominatim import (
    NOMINATIM_REVERSE_URL,
    TOWN_ADDRESS_KEYS,
    TOWN_PREFIX,
    TOWN_SUFFIX,
    clean_town,
    nominatim_reverse_town,
    nominatim_search,
    town_cache_key,
)
from geocoding.pipeline import (
    annotate_tournament,
    geocode_file,
    set_town,
)
from geocoding.places import (
    FED_TO_ISO2,
    MIN_SEGMENT_LETTERS,
    PLACE_TYPES,
    SEGMENT_SPLIT,
    TOO_COARSE,
    candidate_queries,
    split_location,
)

__all__ = [
    "ADMIN_WORDS",
    "AIRPORTS_FILE",
    "AIRPORT_SEARCH_DEG",
    "ARTICLES",
    "ATLANTIC_FEDS",
    "BEACHFRONT_M",
    "COASTLINE_SEARCH_M",
    "COAST_FILE",
    "CONNECTORS",
    "DEFAULT_MAX_LOOKUPS",
    "EARTH_DIAMETER_KM",
    "FED_TO_ISO2",
    "GENERIC_PLACE_WORDS",
    "GEONAMES_COLUMNS",
    "GRID_DEG",
    "LARGE_AIRPORT_DETOUR_KM",
    "MAX_AIRPORT_KM",
    "MAX_NGRAM",
    "MIN_NAME_LEN",
    "MIN_SEGMENT_LETTERS",
    "MISS_RETRY_DAYS",
    "M_PER_DEG_LAT",
    "M_PER_DEG_LNG_EQUATOR",
    "NETWORK_ERRORS",
    "NOMINATIM_REVERSE_URL",
    "NOMINATIM_URL",
    "OVERPASS_RETRY_WAIT_S",
    "OVERPASS_URLS",
    "OVERRIDES_FILE",
    "PLACE_TYPES",
    "PROVINCE_SEATS",
    "REQUEST_INTERVAL_S",
    "SAVE_EVERY",
    "SEASIDE_KM",
    "SEGMENT_SPLIT",
    "TOO_COARSE",
    "TOWN_ADDRESS_KEYS",
    "TOWN_PREFIX",
    "TOWN_SUFFIX",
    "USER_AGENT",
    "VENUE_CATEGORIES",
    "VENUE_MAX_KM",
    "VENUE_NAME_MIN_LEN",
    "VENUE_WORDS",
    "Airports",
    "Coast",
    "Geocoder",
    "Place",
    "annotate_tournament",
    "candidate_queries",
    "clean_town",
    "flags",
    "geocode_file",
    "geonames_match",
    "km_between",
    "load_geonames",
    "logger",
    "metres_to_segment",
    "names_match",
    "nominatim_reverse_town",
    "nominatim_search",
    "normalise",
    "overpass_coastline",
    "sea_distance_m",
    "seaside_coast",
    "set_town",
    "split_location",
    "town_cache_key",
    "town_from_name",
]
